"""Add Stripe columns to members

Revision ID: 21551ec8c0f5
Revises: 17862a79a853
Create Date: 2026-01-04 12:24:13.038135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21551ec8c0f5'
down_revision = '17862a79a853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('current_period_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_period_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_verification_token', sa.String(length=100), nullable=True))

    with op.batch_alter_table('membership_tiers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_product_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('stripe_price_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_tiers', schema=None) as batch_op:
        batch_op.drop_column('stripe_price_id')
        batch_op.drop_column('stripe_product_id')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('cancel_at_period_end')
        batch_op.drop_column('current_period_end')
        batch_op.drop_column('current_period_start')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
